### ISSUE TITLE
Graphical issue when running on Arch Linux

### ISSUE THREAD

**Issue by LouieWoolger** [SnekNOTSnake/my-personal-list#1]
OS: Arch Linux x86_64 
Kernel: 5.16.15-arch1-1 

When I execute the program, it runs fine but does not display properly.

Error in the terminal:
`[41408:0323/005352.945147:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.`

What is displayed:
![Screenshot_2022-03-23_01-04-56](https://user-images.githubusercontent.com/64669505/159601632-39aa975e-3fee-4295-899a-5e2dc2de0ece.png)

**Comment by SnekNOTSnake** [comment]
Is there any element or console error or is it just blank?

Mine runs fine with those error messages. I read that those messages are common on Linux when launching chrome, so I don't think that's the problem.

Edit: It looks like the error only happen on new install (without data). I got a blank page too on my Windows.

**Comment by SnekNOTSnake** [comment]
Fix charts first time install [4e0e134](https://github.com/SnekNOTSnake/my-personal-list/commit/4e0e1346fc68dc5d18ae5c606a93c47c5ef3661c)
